"""update performer_event table

Revision ID: 22b560b98c96
Revises: 4cbc24d578cc
Create Date: 2024-11-13 15:14:15.181014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b560b98c96'
down_revision = '4cbc24d578cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performers_events', schema=None) as batch_op:
        batch_op.alter_column('performer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('host')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performers_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('host', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('performer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
