"""add performer type id to performer table

Revision ID: d1d614060835
Revises: aae4f601dfd5
Create Date: 2024-11-10 22:58:17.014326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d614060835'
down_revision = 'aae4f601dfd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performer_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_performer_performer_type_id_performer_types'), 'performer_types', ['performer_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_performer_performer_type_id_performer_types'), type_='foreignkey')
        batch_op.drop_column('performer_type_id')

    # ### end Alembic commands ###
